config/routes.rb
Rails.application.routes.draw do
  resources :products

  resource :cart, only: [:show, :destroy] do
    collection do
      post :add, path: "/add/:id"
      get :checkout
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      put :cancel
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_item(n)
    found_item = items.find { |item| item.product_id == n }

    if found_item
      found_item.increment
    else
      items << CartItem.new(n)
    end
  end

  def empty?
    items.empty?
  end

  def total_price
    total = items.reduce(0) { |total, item| total + item.total_price }

    if Time.now.month == 1 && total >= 1000
      total -= 100
    else
      total
    end
  end

  def to_hash
    all_items = items.map { |item| { "product_id" => item.product_id,
                                     "quantity" => item.quantity } }

    { "items" => all_items }
  end

  def self.from_hash(hash)
    if hash.nil? or !hash.has_key?("items")
      new
    else
      new hash["items"].map { |item|
        CartItem.new(item["product_id"], item["quantity"])
      }
    end
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize(product_id, quantity = 1)
    @product_id = product_id
    @quantity = quantity
  end

  def increment(n = 1)
    @quantity += n
  end

  def product
    Product.find_by(id: product_id)
  end

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  include AASM

  aasm column: "state" do
    state :pending, initial: true
    state :cancelled, :paid, :shipped, :delivered, :rejected, :refunded

    event :pay do
      transitions from: :pending, to: :paid

      after_transaction do
        puts "send SMS to #{tel}"
      end
    end

    event :ship do
      transitions from: :paid, to: :shipped
    end

    event :deliver do
      transitions from: :shipped, to: :delivered
    end

    event :reject do
      transitions from: :delivered, to: :rejected
    end

    event :refund do
      transitions from: [:rejected, :paid], to: :refunded
    end

    event :cancel do
      transitions from: [:pending, :refunded], to: :cancelled
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :init_cart

  private
  def init_cart
    @cart = Cart.from_hash(session[:cart9487])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add
    @cart.add_item(params[:id])
    session[:cart9487] = @cart.to_hash
    redirect_to products_path, notice: "已放入購物車"
  end

  def checkout
    @order = Order.new
    @token = Braintree::ClientToken.generate
  end

  def destroy
    session[:cart9487] = nil
    redirect_to products_path, notice: "購物車已清除!"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new(order_params)


    @cart.items.each do |item|
      @order.order_items.build(product: item.product,
                               price: item.product.price,
                               quantity: item.quantity)
    end

    if @order.save
      # 1. 付錢
      nonce = params[:payment_method_nonce]


      result = Braintree::Transaction.sale(
        amount: @cart.total_price,
        payment_method_nonce: nonce,
        options: {
          submit_for_settlement: true
        }
      )

      if result.success? || result.transaction
        # 2. 清空購物車
        session[:cart9487] = nil

        # 2.5 寄信通知
        OrderMailer.order_confirm(@order).deliver_now

        # 3. 走回 product 頁面
        redirect_to products_path, notice: "感謝大爺!"
      else
        flash[:notice] = "刷卡發生錯誤"
        render "carts/checkout"
      end
    else
      render "carts/checkout"
    end
  end

  private
  def order_params
    params.require(:order).permit(:recipient, :tel, :email)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: "新增商品完成"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: "商品更新成功"
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: "商品已刪除"
  end

  private
  def find_product
    @product = Product.find_by(id: params[:id])
    redirect_to products_path, notice: "無此商品" unless @product
  end

  def product_params
    params.require(:product).permit(:title, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def badge_link_to(label, count, path)
    link_to "#{label} <span class='badge'>#{count}</span>".html_safe, path
  end
end

app/views/carts/_cart.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>數量</td>
      <td>單價</td>
      <td>小計</td>
    </tr>
  </thead>
  <tbody>
    <% cart.items.each do |item| %>
    <tr>
      <td><%= item.product.title %></td>
      <td><%= item.quantity %></td>
      <td><%= item.product.price %></td>
      <td><%= item.total_price %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">總計</td>
      <td><%= cart.total_price %></td>
    </tr>
  </tfoot>
</table>

app/views/carts/checkout.html.erb
<h1>結帳</h1>

<%= render "cart", cart: @cart %>

<%= simple_form_for @order do |f| %>
  <%= f.input :recipient %>
  <%= f.input :tel %>
  <%= f.input :email %>
  <div id="payment-form"></div>
  <%= f.submit %>
<% end %>

<script src="https://js.braintreegateway.com/js/braintree-2.32.0.min.js"></script>

<script>
var clientToken = "<%= @token %>";
braintree.setup(clientToken, "dropin", { container: "payment-form" });
</script>

app/views/carts/show.html.erb
<h1>購物車</h1>

<%= link_to '清空購物車', cart_path, method: "delete", class:"btn btn-default btn-success" %>

<%= render "cart", cart: @cart %>

<%= link_to '繼續選購', products_path, class:"btn btn-default btn-primary" %>
<%= link_to '結帳', checkout_cart_path, class:"btn btn-default btn-danger" unless @cart.empty? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/navbar" %>

      <%= notice %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for product do |f| %>
  <%= f.input :title, placeholder: "商品名稱" %>
  <%= f.input :price, placeholder: "售價" %>
  <%= f.submit class: "btn btn-default btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1>編輯商品</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>商品列表</h1>

<%= link_to '新增商品', new_product_path, class: "btn btn-default btn-primary" %>

<table class="table table-hover">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>售價</td>
      <td>處理</td>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td>
        <%= link_to '放到購物車', add_cart_path(product), method: "post", class: "btn btn-xs btn-danger" %>
        <%= product.title %>
      </td>
      <td><%= product.price %></td>
      <td>
        <%= link_to '編輯', edit_product_path(product), class: "btn btn-xs btn-default" %>
        <%= link_to '刪除', product, method: "delete", data: { confirm: "確定刪除?" }, class: "btn btn-xs btn-default" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>新增商品</h1>

<%= render "form", product: @product %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">賺超大商店</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= badge_link_to "購物車", @cart.items.count, cart_path %>
        </li>
    </div>
  </div>
</nav>